import Foundation
import Observation

/// Maps a Twitch login to the same streamer's YouTube **channel ID** so the app
/// can recognize when a streamer you follow on Twitch is also a YouTube
/// streamer, and merge their live YouTube presence into one card. The two
/// identities share no common ID, so the mapping comes from a curated table
/// (seeded from the streamer's Twitch profile YouTube links + manual curation).
///
/// Mirrors `KickAliasService`: a scheduled GitHub Action regenerates the table
/// from the current top streamers and publishes a static JSON to the `data`
/// branch. The app only ever **downloads a public static file** — it never
/// uploads what the viewer is watching — preserving the "Data Not Collected"
/// privacy posture.
///
/// Resolution order: freshly-fetched remote (cached on disk) → last cached →
/// the curated copy bundled with the app. So it always has something offline.
@MainActor
@Observable
final class TwitchYouTubeAliasService {
  /// Public, CDN-backed static file regenerated by CI on the `data` branch.
  /// Parameter-free GET — no viewer data is ever sent.
  private static let remoteURL = URL(
    string: "https://raw.githubusercontent.com/thatcube/Twizz/data/twitch-youtube-aliases.json")!
  private static let bundledResource = "TwitchYouTubeAliases"
  private static let cacheFileName = "TwitchYouTubeAliases.cache.json"
  private static let etagDefaultsKey = PersistenceKey.twitchYouTubeAliasETag
  private static let lastFetchDefaultsKey = PersistenceKey.twitchYouTubeAliasLastFetch
  /// Don't re-check the remote more than once a day; the mapping changes slowly.
  private static let minFetchInterval: TimeInterval = 24 * 3600

  /// Lowercased Twitch login -> YouTube channel ID (case preserved).
  private(set) var aliases: [String: String]

  init() {
    aliases = Self.loadCached() ?? Self.loadBundled() ?? [:]
  }

  /// The YouTube channel ID for a streamer's Twitch login, or nil when there's
  /// no known mapping (the caller then renders Twitch-only).
  func youtubeChannelID(forTwitchLogin login: String) -> String? {
    let id = aliases[login.lowercased()]
    return (id?.isEmpty == false) ? id : nil
  }

  /// Conditionally refreshes from the remote (throttled, ETag-aware). Falls back
  /// silently to whatever is already loaded on any failure.
  func refreshIfNeeded() async {
    let defaults = UserDefaults.standard
    if let last = defaults.object(forKey: Self.lastFetchDefaultsKey) as? Date,
      Date().timeIntervalSince(last) < Self.minFetchInterval {
      return
    }

    var request = URLRequest(url: Self.remoteURL)
    request.timeoutInterval = 12
    if let etag = defaults.string(forKey: Self.etagDefaultsKey) {
      request.setValue(etag, forHTTPHeaderField: "If-None-Match")
    }

    guard let (data, response) = try? await NetworkClient.api.data(for: request),
      let http = response as? HTTPURLResponse
    else { return }

    defaults.set(Date(), forKey: Self.lastFetchDefaultsKey)

    guard http.statusCode == 200 else { return }  // 304 -> keep current table
    guard let decoded = Self.decode(data), !decoded.isEmpty else { return }

    Self.writeCache(data)
    if let etag = http.value(forHTTPHeaderField: "ETag") {
      defaults.set(etag, forKey: Self.etagDefaultsKey)
    }
    aliases = decoded
  }

  // MARK: - Loading

  private struct Document: Decodable {
    let map: [String: String]
  }

  private static func decode(_ data: Data) -> [String: String]? {
    guard let document = try? TwitchAPIClient.sharedDecoder.decode(Document.self, from: data) else { return nil }
    var result: [String: String] = [:]
    for (rawKey, rawValue) in document.map {
      let key = rawKey.lowercased()
      // YouTube channel IDs are case-sensitive — preserve the value verbatim.
      let value = rawValue.trimmingCharacters(in: .whitespacesAndNewlines)
      guard !key.isEmpty, !value.isEmpty else { continue }
      result[key] = value
    }
    return result.isEmpty ? nil : result
  }

  private static func loadBundled() -> [String: String]? {
    guard let url = Bundle.main.url(forResource: bundledResource, withExtension: "json"),
      let data = try? Data(contentsOf: url)
    else { return nil }
    return decode(data)
  }

  private static func loadCached() -> [String: String]? {
    guard let url = cacheURL, let data = try? Data(contentsOf: url) else { return nil }
    return decode(data)
  }

  private static var cacheURL: URL? {
    guard
      let dir = try? FileManager.default.url(
        for: .applicationSupportDirectory, in: .userDomainMask, appropriateFor: nil, create: true)
    else { return nil }
    return dir.appendingPathComponent(cacheFileName)
  }

  private static func writeCache(_ data: Data) {
    guard let url = cacheURL else { return }
    try? data.write(to: url, options: .atomic)
  }
}
