import Foundation
import Observation

/// Downloads a public snapshot of which tracked YouTube channels are currently
/// live (and their concurrent viewers), so the app can show a streamer's YouTube
/// presence without ever calling the YouTube Data API from the device.
///
/// **Why a snapshot and not per-device API calls:** YouTube quota is per-project
/// (shared by every user of the app), so per-client calls don't scale. A single
/// backend (a scheduled GitHub Action) checks the shared catalog once and
/// publishes `youtube-live.json` to the `data` branch; the app only ever does a
/// parameter-free GET — N users watching the same streamer cost one central
/// check, and no viewer data is uploaded ("Data Not Collected").
///
/// Resolution order: freshly-fetched remote (cached on disk) → last cached → the
/// copy bundled with the app (intentionally empty so a stale bundle can never
/// assert a false "live").
@MainActor
@Observable
final class YouTubeLiveSnapshotService {
  /// Public, CDN-backed static file regenerated by CI on the `data` branch.
  /// Parameter-free GET — no viewer data is ever sent.
  private static let remoteURL = URL(
    string: "https://raw.githubusercontent.com/thatcube/Twizz/data/youtube-live.json")!
  private static let bundledResource = "YouTubeLive"
  private static let cacheFileName = "YouTubeLive.cache.json"
  private static let etagDefaultsKey = "youTubeLiveETag"
  private static let lastFetchDefaultsKey = "youTubeLiveLastFetch"
  /// Live status is time-sensitive, so refresh far more often than the slow
  /// alias/affinity tables — but still throttle to protect the CDN and battery.
  private static let minFetchInterval: TimeInterval = 120

  /// YouTube channel ID -> current live presence.
  private(set) var presences: [String: YouTubePresence]

  init() {
    presences = Self.loadCached() ?? Self.loadBundled() ?? [:]
  }

  /// The live presence for a YouTube channel ID, or nil when it isn't in the
  /// snapshot (treated as "not live / unknown").
  func presence(forChannelID channelID: String) -> YouTubePresence? {
    presences[channelID]
  }

  /// Conditionally refreshes from the remote (throttled, ETag-aware). Falls back
  /// silently to whatever is already loaded on any failure — presence must never
  /// block the Following rail.
  func refreshIfNeeded() async {
    let defaults = UserDefaults.standard
    if let last = defaults.object(forKey: Self.lastFetchDefaultsKey) as? Date,
      Date().timeIntervalSince(last) < Self.minFetchInterval {
      return
    }

    var request = URLRequest(url: Self.remoteURL)
    request.timeoutInterval = 12
    request.cachePolicy = .reloadIgnoringLocalCacheData
    if let etag = defaults.string(forKey: Self.etagDefaultsKey) {
      request.setValue(etag, forHTTPHeaderField: "If-None-Match")
    }

    guard let (data, response) = try? await URLSession.shared.data(for: request),
      let http = response as? HTTPURLResponse
    else { return }

    defaults.set(Date(), forKey: Self.lastFetchDefaultsKey)

    guard http.statusCode == 200 else { return }  // 304 -> keep current snapshot
    guard let decoded = Self.decode(data) else { return }

    Self.writeCache(data)
    if let etag = http.value(forHTTPHeaderField: "ETag") {
      defaults.set(etag, forKey: Self.etagDefaultsKey)
    }
    presences = decoded
  }

  // MARK: - Loading

  private struct Document: Decodable {
    let streams: [String: Entry]

    struct Entry: Decodable {
      let live: Bool?
      let viewers: Int?
      let videoId: String?
      let title: String?
    }
  }

  private static func decode(_ data: Data) -> [String: YouTubePresence]? {
    guard let document = try? JSONDecoder().decode(Document.self, from: data) else { return nil }
    var result: [String: YouTubePresence] = [:]
    for (rawID, entry) in document.streams {
      let channelID = rawID.trimmingCharacters(in: .whitespacesAndNewlines)
      guard !channelID.isEmpty, entry.live == true else { continue }
      result[channelID] = YouTubePresence(
        channelID: channelID,
        isLive: true,
        viewerCount: entry.viewers,
        videoID: entry.videoId,
        title: entry.title
      )
    }
    // An empty snapshot is valid (nobody tracked is live) — return it so a stale
    // cache of previously-live channels is correctly cleared.
    return result
  }

  private static func loadBundled() -> [String: YouTubePresence]? {
    guard let url = Bundle.main.url(forResource: bundledResource, withExtension: "json"),
      let data = try? Data(contentsOf: url)
    else { return nil }
    return decode(data)
  }

  private static func loadCached() -> [String: YouTubePresence]? {
    guard let url = cacheURL, let data = try? Data(contentsOf: url) else { return nil }
    return decode(data)
  }

  private static var cacheURL: URL? {
    guard
      let dir = try? FileManager.default.url(
        for: .applicationSupportDirectory, in: .userDomainMask, appropriateFor: nil, create: true)
    else { return nil }
    return dir.appendingPathComponent(cacheFileName)
  }

  private static func writeCache(_ data: Data) {
    guard let url = cacheURL else { return }
    try? data.write(to: url, options: .atomic)
  }
}
